apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "cortex-tenant.labels" . | nindent 4 }}
  name: {{ include "cortex-tenant.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "cortex-tenant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations  | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cortex-tenant.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.envs }}
          env:
            {{- range .Values.envs }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          {{- end }}
          {{- if and .Values.config.auth.enabled .Values.config.auth.existingSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.config.auth.existingSecret }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/
              name: config-file
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - configMap:
            name: {{ include "cortex-tenant.fullname" . }}-configmap
          name: config-file
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
